services:
  db:
    container_name: tasks_tracker_db
    image: mysql
    ports:
      - 3333:3306
    environment:
      # Change this to be comming from a .env
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tasks_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: unless-stopped

